name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 20

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
        env:
          NODE_VERSION: 20

      - name: Build and test
        run: |
          dotnet restore
          dotnet build
          dotnet test